<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="600";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/c140820/140U0Lc13430-WC1.jpg ",93,252);
$z[1][4]['ddimg']="/uploads/allimg/c140820/140U0Lc13430-WC1.jpg";
$z[1][4]['text']="图 1";
$z[1][4]['width']="740";
$z[1][4]['height']="3340";

?>