
<field:name itemname="尊称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:content itemname="您的要求" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>
