<div class="coll_bbcl">
                    	<p>[field:pubdate function="MyDate('d',@me)"/]</p>
                       [field:pubdate function="MyDate('Y-m',@me)"/]
                    </div>
                    <div class="coll_bbcr">
                    <a href="[field:arcurl/]"><p>[field:title/]</p></a>
                     <a href="[field:arcurl/]">[field:infos/]...</a>
                    </div>