<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="600";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/c140820/140U0LT1L50-52B1.jpg ",93,252);
$z[1][4]['ddimg']="/uploads/allimg/c140820/140U0LT1L50-52B1.jpg";
$z[1][4]['text']="图 1";
$z[1][4]['width']="700";
$z[1][4]['height']="1684";
$z[2]=Array("img"," /uploads/allimg/c140820/140U0LU34P-62C4.jpg ",254,411);
$z[2][4]['ddimg']="/uploads/allimg/c140820/140U0LU34P-62C4.jpg";
$z[2][4]['text']="图 2";
$z[2][4]['width']="700";
$z[2][4]['height']="1006";
$z[3]=Array("img"," /uploads/allimg/c140820/140U0LV00920-J001.jpg ",413,574);
$z[3][4]['ddimg']="/uploads/allimg/c140820/140U0LV00920-J001.jpg";
$z[3][4]['text']="图 3";
$z[3][4]['width']="700";
$z[3][4]['height']="1006";
$z[4]=Array("img"," /uploads/allimg/c140820/140U0LV45C0-XE4.jpg ",576,732);
$z[4][4]['ddimg']="/uploads/allimg/c140820/140U0LV45C0-XE4.jpg";
$z[4][4]['text']="图 4";
$z[4][4]['width']="700";
$z[4][4]['height']="898";

?>