{dede:pagestyle maxwidth='600' pagepicnum='12' ddmaxwidth='200' row='0' col='0' value='2'/}
{dede:img ddimg='/uploads/allimg/c140820/140U0LT1L50-52B1.jpg' text='图 1' width='700' height='1684'} /uploads/allimg/c140820/140U0LT1L50-52B1.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c140820/140U0LU34P-62C4.jpg' text='图 2' width='700' height='1006'} /uploads/allimg/c140820/140U0LU34P-62C4.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c140820/140U0LV00920-J001.jpg' text='图 3' width='700' height='1006'} /uploads/allimg/c140820/140U0LV00920-J001.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/c140820/140U0LV45C0-XE4.jpg' text='图 4' width='700' height='898'} /uploads/allimg/c140820/140U0LV45C0-XE4.jpg {/dede:img}
