<?php
$z[0]=Array("global","",142,174);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",199,225);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",433,465);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",580,612);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("type","<a class=\"a\" href=\"[field:typelink /]\">ABOUT US</a>",665,751);
$z[4][4]['typeid']="22";
$z[5]=Array("type","<a class=\"b\" href=\"[field:typelink /]\">Client Testimonials</a>",759,856);
$z[5][4]['typeid']="25";
$z[6]=Array("global","",957,979);
$z[6][4]['name']="cfg_tel";
$z[7]=Array("channel","\r\n<a href='[field:typelink/]'>[field:typename/]</a> 	     \r\n                  ",1116,1306);
$z[7][4]['type']="top";
$z[7][4]['row']="8";
$z[7][4]['currentstyle']="<a href='~typelink~' class='cur'>~typename~</a>";

?>